script:
- curl https://api.rollbar.com/api/1/deploy/ -F access_token=f9fff6689aea4905b58eec73f66c791d -F environment=production -F revision=`git log -n 1 --pretty=format:"%H"` -F local_username=$USER
